/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductsApplicationsRouteImport } from './routes/products/applications'
import { Route as ProductsBrandsRouteImport } from './routes/products/brands'
import { Route as ProductsTypesRouteImport } from './routes/products/types'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsApplicationsRoute = ProductsApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBrandsRoute = ProductsBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsTypesRoute = ProductsTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/applications': typeof ProductsApplicationsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/types': typeof ProductsTypesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/applications': typeof ProductsApplicationsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/types': typeof ProductsTypesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blogs': typeof BlogsRoute
  '/contact-us': typeof ContactUsRoute
  '/news': typeof NewsRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/applications': typeof ProductsApplicationsRoute
  '/products/brands': typeof ProductsBrandsRoute
  '/products/types': typeof ProductsTypesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blogs'
    | '/contact-us'
    | '/news'
    | '/products'
    | '/products/applications'
    | '/products/brands'
    | '/products/types'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/blogs'
    | '/contact-us'
    | '/news'
    | '/products'
    | '/products/applications'
    | '/products/brands'
    | '/products/types'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blogs'
    | '/contact-us'
    | '/news'
    | '/products'
    | '/products/applications'
    | '/products/brands'
    | '/products/types'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogsRoute: typeof BlogsRoute
  ContactUsRoute: typeof ContactUsRoute
  NewsRoute: typeof NewsRoute
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/applications': {
      id: '/products/applications'
      path: '/applications'
      fullPath: '/products/applications'
      preLoaderRoute: typeof ProductsApplicationsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/brands': {
      id: '/products/brands'
      path: '/brands'
      fullPath: '/products/brands'
      preLoaderRoute: typeof ProductsBrandsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/types': {
      id: '/products/types'
      path: '/types'
      fullPath: '/products/types'
      preLoaderRoute: typeof ProductsTypesRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsApplicationsRoute: typeof ProductsApplicationsRoute
  ProductsBrandsRoute: typeof ProductsBrandsRoute
  ProductsTypesRoute: typeof ProductsTypesRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsApplicationsRoute: ProductsApplicationsRoute,
  ProductsBrandsRoute: ProductsBrandsRoute,
  ProductsTypesRoute: ProductsTypesRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogsRoute: BlogsRoute,
  ContactUsRoute: ContactUsRoute,
  NewsRoute: NewsRoute,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
